### ISSUE TITLE
Installing VTK Nodes Prequisites on MacOS?

### ISSUE THREAD

**Issue by enzyme69** [simboden/BVtkNodes#3]
Hello, after watching your presentation at Blender Conference 2018, I am slightly curious and eager to try this. Is there any more detailed documentation or some video demonstration about this VTK node?

This line:
VTK (version 7 and above) and VTK python wrappers compatible with the python used in Blender.

Where to download and install VTK for Mac? And how to get the proper VTK Python wrapper? Which version of Blender? I think latest is 3.7.

**Comment by enzyme69** [comment]
Ok I found this old documentation:
https://www.it.uu.se/edu/course/homepage/vetvis/ht10/vtk/instructions_vtk_OSX.pdf

What's slightly tricky is to build this with proper Python, I realized my Python is version 2 while building... I need to use Py Environment or something...

**Comment by simboden** [comment]
Hi! :-)
Sorry, i didn't managed to make it work on osx yet. I am shure it is
feasible but i need to spend more time on it. If you can, try it on ubuntu
in the meantime. And of course if you discover something let me know. Also
have a look at the doc 'building vtk' on github ( linked from the readme )

Regards -- silvano

Il giorno mar 6 nov 2018, 11:11 Jimmy Gunawan <notifications@github.com> ha
scritto:

**Comment by simboden** [comment]
Yes, you are in the right direction. You must compile vtk, and its python
wrapper using a python matching the one used by blender. Let me know, bye
silvano


Il giorno mar 6 nov 2018, 11:44 Jimmy Gunawan <notifications@github.com> ha
scritto:

**Comment by enzyme69** [comment]
@simboden After a couple of hours, I believe I manage to build the VTK for Mac, I can import vtk on Python. But like you said, this version is not working on MacOS? Hmm... I will wait until Mac version is ready then. Not sure how to work on Ubuntu...

**Comment by simboden** [comment]
@enzyme69
When you say " i can import vtk in python" you are un osx? Did you tried importing vtk from the blender python console?-- if it is working, bvtknodes should work too.   Let me know
